### ISSUE TITLE
Use get_variable to limited parameters search range

### ISSUE THREAD

**Issue by ZSTanone** [lu-group/sbinn#10]
Dear Dr.Lu
I noticed you have done some scaling in the definition of parameters.
![image](https://user-images.githubusercontent.com/103397565/200459047-4c28c28a-1c9d-4742-b30c-2535ecbfd885.png)
However in the definition of dynamic equations you didn't rescale the parameters ，shouldn't these two equations be multiplied by 100
，like ` Ub = 100 * get_variable(72 / 100, Ub_)` . Won't it affect the results if you don't scale?

**Comment by mitchelldaneker** [comment]
If you notice not all are scaled by 100. We used change of variables here to simplify the equations a bit.

**Comment by ZSTanone** [comment]
Yes，just some of the parameters did this scale ，but if we didn't rescale them to the original magnitude ，won't this affect the results?

**Comment by ZSTanone** [comment]
By the way ，I meet some problems in doing inverse problem with a complex ode system，I would be very grateful if you could give me some advice！！ @mitchelldaneker 
https://github.com/lululxvi/deepxde/issues/1022#issue-1442188479

**Comment by mitchelldaneker** [comment]
The reason we only do some if that by changing these, it does not change the physical problem statement just the organization of the equations. If we changed all of them, it would change the model in this case but by changing the few we selected, it has no effect on the system. You can check out [this](https://en.wikipedia.org/wiki/Change_of_variables#:~:text=In%20mathematics%2C%20a%20change%20of,to%20a%20better%20understood%20problem.) article on the topic if you need.

As for your inverse problem, I do not know what your equations are but you may need to reweight some of the losses. Just because they are small does not necessarily mean the predictions are good. Some of your losses differ by 2 or 3 orders of magnitude which could be leading to your issues.
