### ISSUE TITLE
Incorrect layer definition in Pytorch implementation

### ISSUE THREAD

**Issue by Vikramank** [lu-group/sbinn#9]
Hello, 
In the pytorch implementation (https://github.com/lu-group/sbinn/blob/main/sbinn/sbinn_pytorch.py#L131), the input layer size is incorrectly defined to be #6. As per the paper only time is the input right? Also in the TF implementation the layer size is one. 
I think the correct version should be 
`net = dde.maps.FNN([1] + [128] * 3 + [6], "swish", "Glorot normal")`

**Comment by mitchelldaneker** [comment]
We use an input transform turning t into 0.01*t, and periodic features of sin(t), sin(2t), etc. In total, we have 6 features which is 6 inputs. Pytorch needs to know that there are 6 inputs. Tensorflow automatically figures out that there are 6 inputs, which is why it appears that there is only 1 input in the code.
